import kotlin.String

/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    const val constraint_layout: String =
            "com.android.support.constraint:constraint-layout:" + Versions.constraint_layout

    /**
     * [espresso-contrib website](https://developer.android.com/testing) */
    const val espresso_contrib: String =
            "com.android.support.test.espresso:espresso-contrib:" + Versions.com_android_support_test_espresso

    /**
     * [espresso-core website](https://developer.android.com/testing) */
    const val espresso_core: String =
            "com.android.support.test.espresso:espresso-core:" + Versions.com_android_support_test_espresso

    /**
     * [rules website](https://developer.android.com/testing) */
    const val com_android_support_test_rules: String =
            "com.android.support.test:rules:" + Versions.com_android_support_test

    /**
     * [runner website](https://developer.android.com/testing) */
    const val com_android_support_test_runner: String =
            "com.android.support.test:runner:" + Versions.com_android_support_test

    /**
     * [appcompat-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val appcompat_v7: String = "com.android.support:appcompat-v7:" + Versions.appcompat_v7

    /**
     * [cardview-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val cardview_v7: String = "com.android.support:cardview-v7:" + Versions.cardview_v7

    /**
     * [design website](http://developer.android.com/tools/extras/support-library.html) */
    const val design: String = "com.android.support:design:" + Versions.design

    const val multidex: String = "com.android.support:multidex:" + Versions.multidex

    /**
     * [percent website](http://developer.android.com/tools/extras/support-library.html) */
    const val percent: String = "com.android.support:percent:" + Versions.percent

    /**
     * [preference-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val preference_v7: String = "com.android.support:preference-v7:" + Versions.preference_v7

    /**
     * [recyclerview-v7 website](http://developer.android.com/tools/extras/support-library.html) */
    const val recyclerview_v7: String =
            "com.android.support:recyclerview-v7:" + Versions.recyclerview_v7

    /**
     * [support-core-utils website](http://developer.android.com/tools/extras/support-library.html) */
    const val support_core_utils: String =
            "com.android.support:support-core-utils:" + Versions.support_core_utils

    /**
     * [support-v4 website](http://developer.android.com/tools/extras/support-library.html) */
    const val support_v4: String = "com.android.support:support-v4:" + Versions.support_v4

    /**
     * [aapt2 website](https://developer.android.com/studio) */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * [gradle website](https://developer.android.com/studio) */
    const val com_android_tools_build_gradle: String =
            "com.android.tools.build:gradle:" + Versions.com_android_tools_build_gradle

    /**
     * [lint-gradle website](https://developer.android.com/studio) */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    const val kotlinandroidviewbindings: String =
            "com.github.MarcinMoskala:KotlinAndroidViewBindings:" + Versions.kotlinandroidviewbindings

    /**
     * [ktlint website](https://github.com/shyiko/ktlint) */
    const val ktlint: String = "com.github.shyiko:ktlint:" + Versions.ktlint

    /**
     * [jsr305 website](http://findbugs.sourceforge.net/) */
    const val jsr305: String = "com.google.code.findbugs:jsr305:" + Versions.jsr305

    const val com_gradle_build_scan_gradle_plugin: String =
            "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:" + Versions.com_gradle_build_scan_gradle_plugin

    /**
     * [threetenabp website](https://github.com/JakeWharton/ThreeTenABP/) */
    const val threetenabp: String =
            "com.jakewharton.threetenabp:threetenabp:" + Versions.threetenabp

    /**
     * [timber website](https://github.com/JakeWharton/timber) */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    /**
     * [logging-interceptor website](https://github.com/square/okhttp) */
    const val logging_interceptor: String =
            "com.squareup.okhttp3:logging-interceptor:" + Versions.com_squareup_okhttp3

    /**
     * [okhttp website](https://github.com/square/okhttp) */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.com_squareup_okhttp3

    /**
     * [converter-moshi website](https://github.com/square/retrofit/) */
    const val converter_moshi: String =
            "com.squareup.retrofit2:converter-moshi:" + Versions.com_squareup_retrofit2

    /**
     * [retrofit website](https://github.com/square/retrofit/) */
    const val retrofit: String =
            "com.squareup.retrofit2:retrofit:" + Versions.com_squareup_retrofit2

    /**
     * [magellan-support website](https://github.com/wealthfront/magellan/) */
    const val magellan_support: String =
            "com.wealthfront:magellan-support:" + Versions.com_wealthfront

    /**
     * [magellan website](https://github.com/wealthfront/magellan/) */
    const val magellan: String = "com.wealthfront:magellan:" + Versions.com_wealthfront

    /**
     * [kotlintest website](http://www.github.com/kotlintest/kotlintest) */
    const val kotlintest: String = "io.kotlintest:kotlintest:" + Versions.kotlintest

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [junit website](http://junit.org) */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * [slimadapter website](https://github.com/MEiDIK/SlimAdapter) */
    const val slimadapter: String = "net.idik:slimadapter:" + Versions.slimadapter

    /**
     * [kotlin-gradle-plugin website](https://kotlinlang.org/) */
    const val kotlin_gradle_plugin: String =
            "org.jetbrains.kotlin:kotlin-gradle-plugin:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlin-stdlib website](https://kotlinlang.org/) */
    const val kotlin_stdlib: String =
            "org.jetbrains.kotlin:kotlin-stdlib:" + Versions.org_jetbrains_kotlin

    /**
     * [kotlinx-coroutines-android website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" + Versions.org_jetbrains_kotlinx

    /**
     * [kotlinx-coroutines-core website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:" + Versions.org_jetbrains_kotlinx

    const val org_jlleitschuh_gradle_ktlint_idea_gradle_plugin: String =
            "org.jlleitschuh.gradle.ktlint-idea:org.jlleitschuh.gradle.ktlint-idea.gradle.plugin:" + Versions.org_jlleitschuh_gradle_ktlint_idea_gradle_plugin

    const val kodein_di_generic_jvm: String =
            "org.kodein.di:kodein-di-generic-jvm:" + Versions.kodein_di_generic_jvm

    /**
     * [kotlin-coroutines-retrofit website](https://github.com/gildor/kotlin-coroutines-retrofit) */
    const val kotlin_coroutines_retrofit: String =
            "ru.gildor.coroutines:kotlin-coroutines-retrofit:" + Versions.kotlin_coroutines_retrofit
}
