import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://github.com/Kotlin/kotlinx.coroutines
     */
    const val kotlinx_coroutines_core: String = "org.jetbrains.kotlinx:kotlinx-coroutines-core:" +
            Versions.org_jetbrains_kotlinx_kotlinx_coroutines

    /**
     * https://developer.android.com/testing
     */
    const val espresso_contrib: String = "com.android.support.test.espresso:espresso-contrib:" +
            Versions.com_android_support_test_espresso

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String = "com.android.support.test.espresso:espresso-core:" +
            Versions.com_android_support_test_espresso

    /**
     * https://developer.android.com/testing
     */
    const val com_android_support_test_rules: String = "com.android.support.test:rules:" +
            Versions.com_android_support_test

    /**
     * https://developer.android.com/testing
     */
    const val com_android_support_test_runner: String = "com.android.support.test:runner:" +
            Versions.com_android_support_test

    /**
     * https://github.com/wealthfront/magellan/
     */
    const val magellan: String = "com.wealthfront:magellan:" + Versions.com_wealthfront

    /**
     * https://github.com/wealthfront/magellan/
     */
    const val magellan_support: String = "com.wealthfront:magellan-support:" +
            Versions.com_wealthfront

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    const val org_jetbrains_kotlin_android_gradle_plugin: String =
            "org.jetbrains.kotlin.android:org.jetbrains.kotlin.android.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_android_gradle_plugin

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val kotlinandroidviewbindings: String =
            "com.github.MarcinMoskala:KotlinAndroidViewBindings:" +
            Versions.kotlinandroidviewbindings

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val support_core_utils: String = "com.android.support:support-core-utils:" +
            Versions.support_core_utils

    /**
     * https://developer.android.com/reference/android/support/constraint/ConstraintLayout.html
     */
    const val constraint_layout: String = "com.android.support.constraint:constraint-layout:" +
            Versions.constraint_layout

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val recyclerview_v7: String = "com.android.support:recyclerview-v7:" +
            Versions.recyclerview_v7

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" + Versions.kotlin_stdlib

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val preference_v7: String = "com.android.support:preference-v7:" + Versions.preference_v7

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val appcompat_v7: String = "com.android.support:appcompat-v7:" + Versions.appcompat_v7

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val cardview_v7: String = "com.android.support:cardview-v7:" + Versions.cardview_v7

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * https://github.com/MEiDIK/SlimAdapter
     */
    const val slimadapter: String = "net.idik:slimadapter:" + Versions.slimadapter

    /**
     * https://github.com/JakeWharton/ThreeTenABP/
     */
    const val threetenabp: String = "com.jakewharton.threetenabp:threetenabp:" +
            Versions.threetenabp

    /**
     * http://www.github.com/kotlintest/kotlintest
     */
    const val kotlintest: String = "io.kotlintest:kotlintest:" + Versions.kotlintest

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val support_v4: String = "com.android.support:support-v4:" + Versions.support_v4

    const val multidex: String = "com.android.support:multidex:" + Versions.multidex

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val percent: String = "com.android.support:percent:" + Versions.percent

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val design: String = "com.android.support:design:" + Versions.design

    /**
     * http://findbugs.sourceforge.net/
     */
    const val jsr305: String = "com.google.code.findbugs:jsr305:" + Versions.jsr305

    /**
     * https://github.com/JakeWharton/timber
     */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    /**
     * https://developer.android.com/studio
     */
    const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

    /**
     * http://junit.org
     */
    const val junit: String = "junit:junit:" + Versions.junit
}
