import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.3"

    const val com_android_support_test_espresso: String = "3.0.2"

    const val com_android_support_test: String = "1.0.2"

    const val com_wealthfront: String = "1.1.0"

    const val com_android_tools_build_gradle: String = "3.5.3"

    const val org_jetbrains_kotlin_android_gradle_plugin: String = "1.3.61"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val kotlinandroidviewbindings: String = "0.12"

    const val support_core_utils: String = "27.1.1"

    const val constraint_layout: String = "1.0.2"

    const val recyclerview_v7: String = "27.0.2"

    const val kotlin_stdlib: String = "1.3.61"

    const val preference_v7: String = "27.0.2"

    const val appcompat_v7: String = "27.0.2"

    const val cardview_v7: String = "28.0.0"

    const val lint_gradle: String = "26.5.3"

    const val slimadapter: String = "2.1.2"

    const val threetenabp: String = "1.2.2"

    const val kotlintest: String = "2.0.7"

    const val support_v4: String = "28.0.0"

    const val multidex: String = "1.0.3"

    const val percent: String = "27.0.2"

    const val design: String = "27.0.2"

    const val jsr305: String = "3.0.2"

    const val timber: String = "4.7.1"

    const val aapt2: String = "3.5.3-5435860"

    const val junit: String = "4.13"

    /**
     * Current version: "6.2"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
