# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/gradle-command
name: Run unit tests on each commit
on:
  pull_request:
    paths:
      - '!**.md'
      - '!.editorconfig'
      - '!**/.gitignore'
      - '!**.adoc'
  push:
    paths:
      - '!**.md'
      - '!.editorconfig'
      - '!**/.gitignore'
      - '!**.adoc'
jobs:
  unittests:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: testDebugUnitTest
